from .MimeType import MimeType

MimeTypeExtensions = {
    MimeType.audio__midi: ["mid", "midi", "kar"],
    MimeType.audio__mpeg: "mp3",
    MimeType.audio__ogg: "ogg",
    MimeType.audio__x_m4a: "m4a",
    MimeType.audio__x_realaudio: "ra",
    MimeType.application__apple_mpegurl: "m3u8",
    MimeType.application__atom_xml: "atom",
    MimeType.application__ggl_earth_kml_xml: "kml",
    MimeType.application__ggl_earth_kmz: "kmz",
    MimeType.application__java_archive: ["jar", "war", "ear"],
    MimeType.application__javascript: "js",
    MimeType.application__json: "json",
    MimeType.application__mac_binhex40: "hqx",
    MimeType.application__ms_excel: "xls",
    MimeType.application__ms_fontobject: "eot",
    MimeType.application__ms_powerpoint: "ppt",
    MimeType.application__msword: "doc",
    MimeType.application__octet_stream: ["bin", "exe", "dll", "deb", "dmg", "iso", "img", "msi", "msp", "msm"],
    MimeType.application__opendocument_graphics: "odg",
    MimeType.application__opendocument_presentation: "odp",
    MimeType.application__opendocument_spreadsheet: "ods",
    MimeType.application__opendocument_text: "odt",
    MimeType.application__openxmlformats_document: "docx",
    MimeType.application__openxmlformats_presentation: "pptx",
    MimeType.application__openxmlformats_sheet: "xlsx",
    MimeType.application__pdf: "pdf",
    MimeType.application__postscript: ["ps", "eps", "ai"],
    MimeType.application__rss_xml: "rss",
    MimeType.application__rtf: "rtf",
    MimeType.application__wap_wmlc: "wmlc",
    MimeType.application__wasm: "wasm",
    MimeType.application__x_7z_compressed: "7z",
    MimeType.application__x_cocoa: "cco",
    MimeType.application__x_java_archive_diff: "jardiff",
    MimeType.application__x_java_jnlp_file: "jnlp",
    MimeType.application__x_makeself: "run",
    MimeType.application__x_perl: ["pl", "pm"],
    MimeType.application__x_pilot: ["prc", "pdb"],
    MimeType.application__x_rar_compressed: "rar",
    MimeType.application__x_rpm: "rpm",
    MimeType.application__x_sea: "sea",
    MimeType.application__x_shockwave_flash: "swf",
    MimeType.application__x_stuffit: "sit",
    MimeType.application__x_tcl: ["tcl", "tk"],
    MimeType.application__x_x509_ca_cert: ["der", "pem", "crt"],
    MimeType.application__x_xpinstall: "xpi",
    MimeType.application__xhtml_xml: "xhtml",
    MimeType.application__xspf_xml: "xspf",
    MimeType.application__zip: "zip",
    MimeType.font__woff: "woff",
    MimeType.font__woff2: "woff2",
    MimeType.image__avif: "avif",
    MimeType.image__gif: "gif",
    MimeType.image__jpeg: ["jpeg", "jpg"],
    MimeType.image__png: "png",
    MimeType.image__svg_xml: ["svg", "svgz"],
    MimeType.image__tiff: ["tif", "tiff"],
    MimeType.image__wap_wbmp: "wbmp",
    MimeType.image__webp: "webp",
    MimeType.image__x_icon: "ico",
    MimeType.image__x_jng: "jng",
    MimeType.image__x_ms_bmp: "bmp",
    MimeType.text__css: "css",
    MimeType.text__html: ["html", "htm", "shtml"],
    MimeType.text__jad: "jad",
    MimeType.text__mathml: "mml",
    MimeType.text__plain: "txt",
    MimeType.text__wap_wml: "wml",
    MimeType.text__x_component: "htc",
    MimeType.text__xml: "xml",
    MimeType.video__3gpp: ["3gpp", "3gp"],
    MimeType.video__mp2t: "ts",
    MimeType.video__mp4: "mp4",
    MimeType.video__mpeg: ["mpeg", "mpg"],
    MimeType.video__quicktime: "mov",
    MimeType.video__webm: "webm",
    MimeType.video__x_flv: "flv",
    MimeType.video__x_m4v: "m4v",
    MimeType.video__x_mng: "mng",
    MimeType.video__x_ms_asf: ["asx", "asf"],
    MimeType.video__x_ms_wmv: "wmv",
    MimeType.video__x_msvideo: "avi",
}
